# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c361a42ca444bf1ec6edd1eae876d70f9e0dab7acefdc5a8c80fb833ebab503fe2f32cae7a3eea11643dcede7d269f9dbea53f615db9fd3573fa5b9c13e8bd4e

test:
  secret_key_base: bedb14c3690282d3cc5009b76d7011f8e68d642c08a8c750c7880ac624e97cb1c60bbfbdc578e81ca12ff4ee7a21a01fc127cc2fc960d038cd9830033351512e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
